import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import Footer from "@/components/Footer";
import FullScreenNav from "@/components/FullScreenNav";
import WhatsAppFloat from "@/components/LandingPage/whatsApp";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <SmoothScroll />
        <div>
          <FullScreenNav />
          <WhatsAppFloat /> 
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
